name: Backend Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd server && npm install

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONG_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: cd server && npm test