name: Frontend Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      working-directory: ./client

    # - name: Start development server
    #   run: npm run dev
    #   working-directory: ./client
    #   # Running this as a background process
    #   background: true

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        browser: chrome
        working-directory: ./client
